### ISSUE TITLE
image_url unavailable

### ISSUE THREAD

**Issue by lordbah** [TheHolyRoger/hass-cryptoinfo#2]
image_url is unavailable for bitcoin and dash.
v0.3.3

**Comment by hardrockhodl** [comment]
is there away to use a custom url?

**Comment by TheHolyRoger** [comment]
The image_url comes from coingecko, only on the sensors with that attribute (price sensors).

@hardrockhodl I'm using custom icons on all my sensors in home assistant, is that what you mean?

**Comment by TheHolyRoger** [comment]
Sorry i realised there was actually a bug here, fixed in https://github.com/TheHolyRoger/hass-cryptoinfo/releases/tag/v0.3.6
