### ISSUE TITLE
ID bitcoin1900_es_pm_athi

### ISSUE THREAD

**Issue by duczz** [TheHolyRoger/hass-cryptoinfo#7]
ID bitcoin1900_es_pm_athi is nowhere eixsting

Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:719
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 17:57:53 (2 Vorkommnisse)
Zuletzt protokolliert: 17:57:53

Platform cryptoinfo_advanced does not generate unique IDs. ID bitcoin1900_es_pm_athi already exists - ignoring sensor.cryptoinfo_bitcoin_all_time_high
Platform cryptoinfo_advanced does not generate unique IDs. ID bitcoin1900_es_pm_athdi already exists - ignoring sensor.cryptoinfo_bitcoin_all_time_high_distance

**Comment by TheHolyRoger** [comment]
Can you show me the config for this?

**Comment by duczz** [comment]
I don't use it anymore
